stages:
  - test

variables:
  FLASK_APP: manage.py
  FLASK_ENV: testing

test_backend:
  stage: test
  image: python:3.10
  before_script:
    - echo "Устанавливаю зависимости"
    - pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - cd backend
  script:
    - pytest -v tests/unit
  timeout: 10 minutes
