stages:
  - test

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
  FLASK_APP: manage.py
  FLASK_ENV: testing

services:
  - postgres:15

test_backend:
  stage: test
  image: python:3.10
  before_script:
    - pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - cd backend
    # Ждём, пока Postgres будет готов
    - until pg_isready -h postgres -U postgres; do sleep 1; done
    # Применяем миграции, если есть
    - flask db upgrade
  script:
    - PYTHONPATH=. pytest
