services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: flask run --host=0.0.0.0 --port=5050
    volumes:
      - ./backend:/app
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      - FLASK_APP=manage:create_app
      - FLASK_ENV=development

volumes:
  postgres_data:
    name: book_exchange_postgres_data