"""Add status field to Exchange

Revision ID: 26316f4d00a7
Revises: bb1ed50daf1c
Create Date: 2025-05-18 01:43:41.751745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26316f4d00a7'
down_revision = 'bb1ed50daf1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
